name: application-deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Clean workspace
      uses: AutoModality/action-clean@v1

    - name: checkout directory
      uses: actions/checkout@v2

    - name: docker build no cache
      run: docker build -t tvbot .
      
    - name: docker compose up detach
      run: docker run -e API_TOKEN=${{ secrets.API_TOKEN }} -e API_KEY=${{ secrets.API_KEY }}  -d --rm tvbot